- name: update prometheus configuration
  ansible.buitlin.template:
  src: prometheus.yml
  dest: /opt/prometheus/prometheus.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted